// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EStoreShoppingSys.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("EditItemsInCart")]
    public partial class EditItemsInCartFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "CartItemEdit.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EditItemsInCart", "\tIn order to select and discart the product as I like \r\n\tAs customer\r\n\tI want to " +
                    "add and delete product in the cart", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
#line 8
 testRunner.Given("Register And Login And Create Cart", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C25 Success to Add Items into the cart")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public virtual void C25SuccessToAddItemsIntoTheCart()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C25 Success to Add Items into the cart", null, new string[] {
                        "Smoke"});
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table1.AddRow(new string[] {
                            "1",
                            "1",
                            "550",
                            "550"});
                table1.AddRow(new string[] {
                            "2",
                            "99",
                            "24.95",
                            "2470.05"});
                table1.AddRow(new string[] {
                            "3",
                            "999",
                            "22.5",
                            "22477.5"});
                table1.AddRow(new string[] {
                            "4",
                            "9999",
                            "14.99",
                            "149885.01"});
                table1.AddRow(new string[] {
                            "5",
                            "99999",
                            "27.9",
                            "2789972.1"});
#line 11
 testRunner.Given("add the valid items table to cart", ((string)(null)), table1, "Given ");
#line hidden
#line 18
 testRunner.Then("should get  response of \'OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
 testRunner.And("should get response comform with model \'CartItemAdd\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
 testRunner.And("add  item:  [\'datas\'] [\'cartId,accountNumber\'] in response body to scenario conte" +
                        "xt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
 testRunner.And("should keep value constant for keys \'cartId,accountNumber\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table2.AddRow(new string[] {
                            "1",
                            "1",
                            "550",
                            "550"});
                table2.AddRow(new string[] {
                            "2",
                            "99",
                            "24.95",
                            "2470.05"});
                table2.AddRow(new string[] {
                            "3",
                            "999",
                            "22.5",
                            "22477.5"});
                table2.AddRow(new string[] {
                            "4",
                            "9999",
                            "14.99",
                            "149885.01"});
                table2.AddRow(new string[] {
                            "5",
                            "99999",
                            "27.9",
                            "2789972.1"});
#line 22
 testRunner.And("CartInfo items in cart should be same to the table", ((string)(null)), table2, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C26 Should fail to add items to cart with invalid credential")]
        [NUnit.Framework.CategoryAttribute("ShouldFail")]
        public virtual void C26ShouldFailToAddItemsToCartWithInvalidCredential()
        {
            string[] tagsOfScenario = new string[] {
                    "ShouldFail"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C26 Should fail to add items to cart with invalid credential", null, new string[] {
                        "ShouldFail"});
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table3.AddRow(new string[] {
                            "1",
                            "1",
                            "550",
                            "550"});
#line 33
testRunner.Given("CARTADDITEM add the valid items table to cart with invalid credential", ((string)(null)), table3, "Given ");
#line hidden
#line 36
testRunner.Then("should get  response of \'CredentialError\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C27 Should fail to add items to cart with invalid itemid")]
        [NUnit.Framework.CategoryAttribute("ShouldFail")]
        public virtual void C27ShouldFailToAddItemsToCartWithInvalidItemid()
        {
            string[] tagsOfScenario = new string[] {
                    "ShouldFail"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C27 Should fail to add items to cart with invalid itemid", null, new string[] {
                        "ShouldFail"});
#line 39
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table4.AddRow(new string[] {
                            "999999",
                            "1",
                            "550",
                            "550"});
#line 40
testRunner.Given("CARTADDITEM add the invalid items table to cart", ((string)(null)), table4, "Given ");
#line hidden
#line 43
testRunner.Then("should get  response of \'InvalidItemError\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C28 Should fail to add items to cart with invalid cartid")]
        [NUnit.Framework.CategoryAttribute("ShouldFail")]
        public virtual void C28ShouldFailToAddItemsToCartWithInvalidCartid()
        {
            string[] tagsOfScenario = new string[] {
                    "ShouldFail"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C28 Should fail to add items to cart with invalid cartid", null, new string[] {
                        "ShouldFail"});
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table5.AddRow(new string[] {
                            "1",
                            "1",
                            "550",
                            "550"});
#line 47
testRunner.Given("CARTADDITEM add the items in table to cart with invalid cartid", ((string)(null)), table5, "Given ");
#line hidden
#line 50
testRunner.Then("should get  response of \'InvalidCartError\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C29 Success to Delete Items from the cart")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public virtual void C29SuccessToDeleteItemsFromTheCart()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C29 Success to Delete Items from the cart", null, new string[] {
                        "Smoke"});
#line 53
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table6.AddRow(new string[] {
                            "1",
                            "1",
                            "550",
                            "550"});
                table6.AddRow(new string[] {
                            "2",
                            "99",
                            "24.95",
                            "2470.05"});
                table6.AddRow(new string[] {
                            "3",
                            "999",
                            "22.5",
                            "22477.5"});
#line 54
 testRunner.Given("add the valid items table to cart", ((string)(null)), table6, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table7.AddRow(new string[] {
                            "1",
                            "1",
                            "550",
                            "550"});
#line 59
 testRunner.When("CARTADDITEM delete the items in table from cart", ((string)(null)), table7, "When ");
#line hidden
#line 62
 testRunner.Then("should get  response of \'OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 63
 testRunner.And("should get response comform with model \'CartItemDelete\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 64
 testRunner.And("add  item:  [\'datas\'] [\'cartId,accountNumber\'] in response body to scenario conte" +
                        "xt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 65
 testRunner.And("should keep value constant for keys \'cartId,accountNumber\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table8.AddRow(new string[] {
                            "2",
                            "99",
                            "24.95",
                            "2470.05"});
                table8.AddRow(new string[] {
                            "3",
                            "999",
                            "22.5",
                            "22477.5"});
#line 66
 testRunner.And("CartInfo items in cart should be same to the table", ((string)(null)), table8, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C30 Should fail to delete items from cart with invalid credential")]
        [NUnit.Framework.CategoryAttribute("ShouldFail")]
        public virtual void C30ShouldFailToDeleteItemsFromCartWithInvalidCredential()
        {
            string[] tagsOfScenario = new string[] {
                    "ShouldFail"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C30 Should fail to delete items from cart with invalid credential", null, new string[] {
                        "ShouldFail"});
#line 72
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table9.AddRow(new string[] {
                            "1",
                            "1",
                            "550",
                            "550"});
#line 73
 testRunner.Given("add the valid items table to cart", ((string)(null)), table9, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table10.AddRow(new string[] {
                            "1",
                            "1",
                            "550",
                            "550"});
#line 76
 testRunner.Given("CARTADDITEM delete the valid items table from cart with invalid credential", ((string)(null)), table10, "Given ");
#line hidden
#line 79
testRunner.Then("should get  response of \'CredentialError\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C31 Should fail to delete items from empty cart")]
        [NUnit.Framework.CategoryAttribute("ShouldFail")]
        public virtual void C31ShouldFailToDeleteItemsFromEmptyCart()
        {
            string[] tagsOfScenario = new string[] {
                    "ShouldFail"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C31 Should fail to delete items from empty cart", null, new string[] {
                        "ShouldFail"});
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table11.AddRow(new string[] {
                            "2",
                            "1",
                            "550",
                            "550"});
#line 85
 testRunner.Given("CARTADDITEM delete the unexisting items  from cart", ((string)(null)), table11, "Given ");
#line hidden
#line 88
testRunner.Then("should get  response of \'InvalidItemError\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C42 Should fail to delete invalid items from cart")]
        [NUnit.Framework.CategoryAttribute("ShouldFail")]
        public virtual void C42ShouldFailToDeleteInvalidItemsFromCart()
        {
            string[] tagsOfScenario = new string[] {
                    "ShouldFail"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C42 Should fail to delete invalid items from cart", null, new string[] {
                        "ShouldFail"});
#line 91
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table12.AddRow(new string[] {
                            "1",
                            "1",
                            "550",
                            "550"});
#line 92
 testRunner.Given("add the valid items table to cart", ((string)(null)), table12, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "itemId",
                            "quantity",
                            "price",
                            "amount"});
                table13.AddRow(new string[] {
                            "0",
                            "1",
                            "550",
                            "550"});
#line 95
testRunner.And("CARTADDITEM delete the invalid items in table from cart", ((string)(null)), table13, "And ");
#line hidden
#line 98
testRunner.Then("should get  response of \'InvalidItemError\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
